name: MikeyMcPlus
main: xyz.michaelzhao.mikeymcplus.MikeyMcPlus
version: 0.0.3-SNAPSHOT
author: Michael Zhao
description: My first mc plugin!

commands:
  fun:
    description: Fun little commands (like gaystick and firework)
    usage: /fun <firework | gaystick>
  games:
    description: A minigame engine
    usage: /games [tool]