name: MikeyMinigames
main: xyz.michaelzhao.mikeyminigames.MikeyMinigames
version: 15.0.10-SNAPSHOT
author: Michael Zhao
description: My first mc plugin!

commands:
  fun:
    description: Fun little commands
    usage: /fun <firework | gaystick>
  games:
    description: A minigame engine
    usage: /games <commands>