main: xyz.michaelzhao.mikeymcplus.MikeyMcPlus
name: MikeyMcPlus
version: 0.0.3-SNAPSHOT
author: Michael Zhao
description: My first mc plugin!

commands:
  firework:
    description: Firework generator!
    usage: /firework
  gaystick:
    description: Gives you a powerful stick!
    usage: /gaystick <knockback level>